Add the s3 provider to the contrib distro
open-telemetry/opentelemetry-collector-releases pull request #546
Opened 2024-05-07 18:13 UTC by evan-bradley

The s3 provider has not had any major changes for at least a year now, I think it should likely be safe to include it in the contrib distribution.

@Aneurysm9 as the codeowner, please block this if you think this component is not ready for wider use.

2024-05-07 18:23 UTC, mx-psi requested changes
I think we should add it to contrib's test build before adding it here

2024-05-07 18:27 UTC, evan-bradley commented
>I think we should add it to contrib's test build before adding it here

Agreed, I have this PR open to do that: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32916. Probably should have included that in the PR description, sorry.

I'd like to have that merged before we merge this, but I would like to at least start the discussion of what prerequisites we'd like when including these in our distributions.

2024-05-07 18:28 UTC, evan-bradley commented
I'll convert this to a draft while https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32916 is in progress, and until we have consensus.

2024-05-07 21:40 UTC, atoulme commented
Happy to review once we have https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32916 merged. Excited for those changes!

2024-06-04 17:55 UTC, atoulme commented
Please update the versions and we can get this in.

2024-06-04 18:54 UTC, evan-bradley commented
Thanks for the reminder, I got diverted and lost track of this one; sorry for the lack of an update

My plan before marking this as ready was to promote the provider to alpha, but in order to do that, mdatagen needs to support providers. We could look at accelerating the timeline there if you would like, otherwise I was going to pick that back up after I wrap up some other work.

2024-08-20 21:52 UTC, eduardoasantana commented
Has there been any movement on this?

2024-11-18 10:19 UTC, gordash2013 commented
Hello, if there are any updates on this feature?

2025-02-25 01:54 UTC, evan-bradley commented
@Jonnobrow Sorry for the long delay. https://github.com/open-telemetry/opentelemetry-collector/pull/12467 is the first step to address this.

2025-02-26 22:45 UTC, evan-bradley commented
@mx-psi @atoulme this is ready for review now.

2025-02-27 02:54 UTC, atoulme approved these changes

2025-02-27 03:49 UTC, dmitryax approved these changes

2025-02-27 12:47 UTC, mx-psi approved these changes

2025-02-27 12:47 UTC, mx-psi commented on internal/tools/go.sum
Is this change intentional?

2025-02-27 13:15 UTC, evan-bradley commented on internal/tools/go.sum
Yes, it was required to get chloggen working again. I'm not sure how this got out of sync.

2025-02-27 13:18 UTC, mx-psi commented on internal/tools/go.sum
That's weird, but makes sense to fix it here then, thanks for clarifying!

2025-02-27 14:10 UTC, merged